// prettier-ignore
export const STRINGS = {
    'search.placeholder': 'Search',
    'turn.off': 'Turn off',
    'turn.on': 'Turn on',
    'reboot': 'Reboot',
    'empty.table': 'Nothing to show',
    'name': 'Name',
    'status': 'Status',
    'movies': 'Movies',
    'movies.count': 'Number of elements',
    'label': 'WatchMe',
    'view.all': 'View all' ,
    'view.favorites': 'View Favorites' ,
    'view.page.on.itunes': 'View page on Itunes' ,
    'release.date': 'Release date:' ,
    'user.ratings': 'User rating:' ,
    'we.give': `We give ` ,
    'will.like': ' that you will like this movie',
    'hover.video': 'Hover over video to play sound',
    'match': 'Match:',
    'read.more': 'Read more',
    'unlike': 'Unlike',
    'like': 'Like',
    'back.to.main': 'Back to main',
    'results.found': 'Results found: ',
}
